server.port=8080
spring.application.name=api-gateway
server.error.include-stacktrace=never
server.error.include-message=always

spring.cloud.gateway.routes[0].id=catalog-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/catalog/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/order/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=catalog-api-docs
spring.cloud.gateway.routes[2].uri=http://localhost:8081
spring.cloud.gateway.routes[2].predicates[0]=Path=/catalog/v3/api-docs
spring.cloud.gateway.routes[2].filters[0]=RewritePath=/catalog/v3/api-docs,/v3/api-docs

spring.cloud.gateway.routes[3].id=order-api-docs
spring.cloud.gateway.routes[3].uri=http://localhost:8082
spring.cloud.gateway.routes[3].predicates[0]=Path=/order/v3/api-docs
spring.cloud.gateway.routes[3].filters[0]=RewritePath=/order/v3/api-docs,/v3/api-docs